# Generated by Django 5.2 on 2025-06-04 09:32

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('easybook', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(open('/app/web/easybook/check_booking_capacity.sql').read()),
    ]
