# Generated by Django 5.2 on 2025-07-03 11:41
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easybook', '0001_initial'),
    ]

    operations = [
        BtreeGistExtension(),
    ]
