# Generated by Django 5.2 on 2025-07-03 11:44

import django.contrib.postgres.constraints
import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easybook', '0002_install_gist'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=django.contrib.postgres.indexes.GistIndex(fields=['timerange'], name='easybook_bo_timeran_caa26e_gist'),
        ),
        migrations.AddIndex(
            model_name='capacitywindow',
            index=django.contrib.postgres.indexes.GistIndex(fields=['timerange'], name='easybook_ca_timeran_5fe546_gist'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=(('user', '='), ('resource', '='), ('timerange', '&&')), name='prevent_overlap_for_the_same_user'),
        ),
        migrations.AddConstraint(
            model_name='capacitywindow',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=(('resource', '='), ('timerange', '&&')), name='prevent_capacity_windows_overlap'),
        ),
    ]
