# Generated by Django 5.2 on 2025-10-12 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybook', '0005_company_companymembership_resourcestaff_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='pricing',
            field=models.CharField(blank=True, choices=[('per service', 'Per service'), ('per minute', 'Per minute'), ('per hour', 'Per hour'), ('per day', 'Per day')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_categories', to='easybook.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='easybook.category')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybook.category')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybook.resource')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='resources', through='easybook.ResourceCategory', to='easybook.category'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['company', 'parent', 'is_active', 'sort_order'], name='easybook_ca_company_14a51c_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('company', 'parent', 'name'), name='uniq_sibling_category_name_per_company'),
        ),
        migrations.AddIndex(
            model_name='resourcecategory',
            index=models.Index(fields=['resource'], name='easybook_re_resourc_648297_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcecategory',
            index=models.Index(fields=['category'], name='easybook_re_categor_5682ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourcecategory',
            constraint=models.UniqueConstraint(fields=('resource', 'category'), name='uniq_resource_category_pair'),
        ),
    ]
