# Generated by Django 5.2 on 2025-10-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easybook', '0006_resource_is_active_resource_old_price_resource_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization_name',
        ),
    ]
