# Generated by Django 5.2 on 2025-10-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easybook', '0007_remove_user_organization_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='url',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='address',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='url',
        ),
    ]
