# Generated by Django 5.2 on 2025-10-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybook', '0009_alter_category_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
