# Generated by Django 5.2 on 2025-10-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easybook', '0010_alter_company_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='pricing',
            new_name='pricing_type',
        ),
    ]
