# Generated by Django 5.2 on 2025-10-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybook', '0011_rename_pricing_resource_pricing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='pricing_type',
            field=models.CharField(blank=True, choices=[('per service', 'Per service'), ('per minute', 'Per minute'), ('per hour', 'Per hour'), ('per day', 'Per day')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='staff',
            name='company_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
