# Generated by Django 5.2 on 2025-10-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easybook', '0012_alter_booking_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
